// <auto-generated />
using System;
using MemberRewardApproval.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemberRewardApproval.WebApi.Migrations
{
    [DbContext(typeof(RewardsDbContext))]
    partial class RewardsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MemberRewardApproval.WebApi.Models.DailySequence", b =>
                {
                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastSequence")
                        .HasColumnType("int");

                    b.HasKey("EntityName", "Date");

                    b.ToTable("DailySequences");
                });

            modelBuilder.Entity("MemberRewardApproval.WebApi.Models.MemberPerformanceSnapshot", b =>
                {
                    b.Property<string>("SnapshotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ADT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgBet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Playtime")
                        .HasColumnType("time");

                    b.Property<decimal>("TheoWin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WinLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WynnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SnapshotId");

                    b.ToTable("MemberPerformanceSnapshots");

                    b.HasData(
                        new
                        {
                            SnapshotId = "11111111-1111-1111-1111-111111111111",
                            ADT = 3000m,
                            AvgBet = 5000m,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Playtime = new TimeSpan(0, 12, 0, 0, 0),
                            TheoWin = 18000m,
                            WinLoss = -20000m,
                            WynnId = "12345678"
                        });
                });

            modelBuilder.Entity("MemberRewardApproval.WebApi.Models.RewardRequest", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WynnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("RewardRequests");
                });

            modelBuilder.Entity("MemberRewardApproval.WebApi.Models.Supervisor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supervisors");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AadId = "6f6a353c0843453e",
                            Email = "eddiegengar@gmail.com",
                            Name = "Supervisor1"
                        });
                });

            modelBuilder.Entity("MemberRewardApproval.WebApi.Models.RewardRequest", b =>
                {
                    b.OwnsOne("MemberRewardApproval.WebApi.Models.RequestedValue", "RequestedValue", b1 =>
                        {
                            b1.Property<string>("RewardRequestRequestId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RewardRequestRequestId");

                            b1.ToTable("RewardRequests");

                            b1.WithOwner()
                                .HasForeignKey("RewardRequestRequestId");
                        });

                    b.Navigation("RequestedValue")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
